name: Launch EC2 Instance

on:
  push:
    paths:
      - 'launch_ec2.py'
  workflow_dispatch:
    inputs:
      instance_type:
        description: 'EC2 Instance Type'
        required: false
        default: 't2.micro'

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install boto3

    - name: Launch EC2 Instance
      run: |
        python launch_ec2.py ${{ github.event.inputs.instance_type }}

